### PR TITLE
Part 1 Add/Remove Roles:

### PR DESCRIPTION
**Pull request by MyChakoTaco**
- Created rolesJSON.py to handle interaction with roles.json file.
- Add roles.json to record roles and guilds
- add addRole and removeRole commands to roles_cog.py

TODO:
- Fix some logic errors in rolesJSON.py addRole() related to setting role fields
- add an editRole

### CODE REVIEW

**Comment by CasparHansen** [comment]
I was gonna ask about this before it was closed, but I don't think the roles.json is necessary since there's already Discord APIs to list/modify roles on the server.

**Comment by MyChakoTaco** [comment]
sorry i clicked the wrong thing lol. 

@CasparHansen we currently use roles.py to determine special "game" roles. the iam, whois, games, and iamnot commands are supposed to interact with these low-permission roles and not interfere with high-permission roles in the server. roles.json would allow users to add/remove/edit these low-permission roles without requiring an admin role.

**Comment by MyChakoTaco** [comment]
for example, we don't want someone going ".iam moderator" and get a moderator role. we would want to restrict the commands to low-permission roles (primarily used for mentions) like ".iam valorant" or ".iam minecraft"

**Comment by CasparHansen** [comment]
I think that may be able to be handled through the bot commands checking the permissions levels through the API and only creating/assigning roles with the right permissions set and that limited blacklist of permissions not to allow will be easier to manage than a large whitelist.

**Comment by MyChakoTaco** [comment]
@danny-tom @kennethbored what do you think? i remember thinking we could do it based off permissions, but now i forgot why we don't do this. is it because we didn't want people to do weird stuff? the other reason for making a json now is because of the party system which allows preset-ing party dimensions (valorant has party size 5, fallguys has party size 4) and thumbnail image. discord wouldn't be able to hold these user-defined preset data

**Comment by kennethbored** [comment]
I think we can do it based off permissions. I can't actually remember anymore why we don't. Currently the role hierarchy on discord is set like this:

image

Charon has the Staff role and would technically only be able to manage roles belong it (which is valorant/overwatch/projectwinter). I don't actually remember if someone could do '.iam staff'

**Comment by MyChakoTaco** [comment]
I can change all our role management to be purely through discord.py putting the newly created/deleted roles on positions below Staff with restricted permissions. the commands iam, iamnot, whois, games, and future features would only work on roles with limited permissions and are below Staff

**Comment by kennethbored** [comment]
Okay I was talking to Danny and I remember why we did it this way. 

So there is a flag in discord role permissions to "manage roles" but it doesn't make a distinction between creating roles and editing them. Allowing the bot to create any role would open the door for someone to maliciously create hundreds of roles with the bot as a proxy.

**Comment by CasparHansen** [comment]
Wouldn't you also have to solve that problem with manually implementing the role permissions as in this PR anyway? Or is arbitrary role creation not in scope for the bot?

**Comment by kennethbored** [comment]
I think arbitrary role creation isn't in the scope for the bot

**Pull request closed without merging**
